---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodump-cron
  namespace: mongodb
spec:
  schedule: "1  7  *  *  *"  # Run daily at 07:01
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: rclone-config
              secret:
                secretName: cloudflare-r2-rw
          containers:
            - name: mongodump-widget
              image: ghcr.io/kyoobit/mongodump-widget:latest
              env:
                - name: MONGO_RO_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: mongodb-readonly
                      key: username
                - name: MONGO_RO_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mongodb-readonly
                      key: password
                - name: ENCRYPTION_PUBLIC_KEY
                  valueFrom:
                    secretKeyRef:
                      name: data-encryption
                      key: public
                - name: OSS
                  valueFrom:
                    configMapKeyRef:
                      name: cloudflare-r2-dumps
                      key: oss
                - name: OSS_BUCKET
                  valueFrom:
                    configMapKeyRef:
                      name: cloudflare-r2-dumps
                      key: oss_bucket
                - name: OSS_PATH
                  valueFrom:
                    configMapKeyRef:
                      name: cloudflare-r2-dumps
                      key: oss_path
                - name: MONGO_DB
                  valueFrom:
                    configMapKeyRef:
                      name: cloudflare-r2-dumps
                      key: mongo_db
                - name: MONGO_COL
                  valueFrom:
                    configMapKeyRef:
                      name: cloudflare-r2-dumps
                      key: mongo_col
                - name: MONGO_ADDR
                  valueFrom:
                    configMapKeyRef:
                      name: cloudflare-r2-dumps
                      key: mongo_uri
                - name: RETENTION_PERIOD
                  valueFrom:
                    configMapKeyRef:
                      name: cloudflare-r2-retention
                      key: retention_period
              volumeMounts:
                - name: rclone-config
                  mountPath: "/etc/rclone"
                  readOnly: true
